### ISSUE TITLE
How can i fix "cannot import name 'StableCascadeDecoderPipeline' from 'diffusers' "

### ISSUE THREAD

**Issue by pinea00** [DenOfEquity/StableCascade-for-webUI#1]
How can I fix this error ? thanks😢(forge)
*** Error loading script: stablecascade_diffusers.py
    Traceback (most recent call last):
      File "S:\forge\modules\scripts.py", line 544, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "S:\forge\modules\script_loading.py", line 10, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "S:\stable-diffusion-webui\extensions\StableCascade-for-webUI\scripts\stablecascade_diffusers.py", line 5, in <module>
        from diffusers import StableCascadeDecoderPipeline, StableCascadePriorPipeline, StableCascadeUNet#, DDPMWuerstchenScheduler
    ImportError: cannot import name 'StableCascadeDecoderPipeline' from 'diffusers' (venv\lib\site-packages\diffusers\__init__.py)

**Comment by DenOfEquity** [comment]
It seems like you have an old release of *diffusers* installed with Forge.
In the ```forge/webui``` directory there is a file called ```requirements_versions.txt```, look for the line ```diffusers==0.25.0``` (probably the last line) and edit it to ```diffusers>=0.28.1```. If the line doesn't exist, just add it. Fully restart Forge. On start, Forge will install the newer version.
I'll update the install instructions in the README too.
